apiVersion: v1
kind: ConfigMap
metadata:
  name: video-vault-runtime
  labels:
    app.kubernetes.io/name: video-vault
    app.kubernetes.io/part-of: video-vault
data:
  MAX_UPLOAD_SIZE_BYTES: "21474836480"
  UPLOAD_PART_SIZE_BYTES: "8388608"
