apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: video-vault
resources:
  - config.yaml
  - deployment.yaml
  - ingress.yaml
  - migration.yaml
  - network-policy.yaml
  - release-verification.yaml
  - service.yaml
